#' Setup command for package
#'
#' Sets working directory, adds output folders, downloads gpx.fmt and yolov3 weights file
#' @param video_location The directory and name of the video file including extension
#' @examples
#' vid_setup("C:/videos/video.mp4");
#' @export

vid_setup <- function(video_location){
    setwd(dirname(video_location));
    dir.create("../output")
    dir.create("../output/videoframes")
    dir.create("../output/boxedimages")
    video_path <<- video_location
    video_image_destination <<- "../output/videoframes"
#    download.file(
#      "https://pjreddie.com/media/files/yolov3.weights",
#      "../output"
#    )
    yolo_weights <<- "../yolov3.weights"
    boxed_images <<- "../output/boxedimages"
#    download.file(
#      "https://raw.githubusercontent.com/exiftool/exiftool/master/fmt_files/gpx.fmt",
#      "../output"
#    )
    gpx_path <<- "../gpx.fmt"
}


##currently needs weights and fmt files manually placed in video directory
## gpx_path is broken. needs to point to a gpx file in /output/ that is generated by exiftoolr.
